# Generated by Django 5.0.14 on 2025-11-29 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorAccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Correo del profesor al que se envió el código', max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('access_code', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El código de acceso debe contener solo números', regex='^\\d+$')], verbose_name='Código de Acceso')),
                ('is_used', models.BooleanField(default=False, help_text='Indica si el código ya fue utilizado para registrarse', verbose_name='Usado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Código de Acceso de Profesor',
                'verbose_name_plural': 'Códigos de Acceso de Profesores',
                'db_table': 'professor_access_codes',
                'indexes': [models.Index(fields=['email'], name='professor_a_email_a5c55d_idx'), models.Index(fields=['access_code'], name='professor_a_access__60970d_idx'), models.Index(fields=['is_used'], name='professor_a_is_used_157546_idx')],
            },
        ),
    ]
