# Generated by Django 5.0.14 on 2025-11-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_create_professor_for_existing_administrators'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='professoraccesscode',
            index=models.Index(fields=['access_code', 'is_used', 'email'], name='prof_access_code_lookup_idx'),
        ),
    ]
