# Generated by Django 5.0.14 on 2025-11-04 00:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('challenges', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('tokens_total', models.IntegerField(default=0, verbose_name='Tokens Totales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=50, unique=True, verbose_name='Código de Sala')),
                ('qr_code', models.TextField(blank=True, null=True, verbose_name='Código QR')),
                ('status', models.CharField(choices=[('lobby', 'Lobby'), ('running', 'En Curso'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='lobby', max_length=20, verbose_name='Estado')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciada en')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizada en')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='game_sessions', to='academic.course', verbose_name='Curso')),
                ('current_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_sessions', to='challenges.activity', verbose_name='Actividad Actual')),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_sessions', to='challenges.stage', verbose_name='Etapa Actual')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='game_sessions', to='users.professor', verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Sesión de Juego',
                'verbose_name_plural': 'Sesiones de Juego',
                'db_table': 'game_sessions',
            },
        ),
        migrations.CreateModel(
            name='SessionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('completed', 'Completada')], default='pending', max_length=20, verbose_name='Estado')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciada en')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completada en')),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_stages', to='game_sessions.gamesession', verbose_name='Sesión de Juego')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='session_stages', to='challenges.stage', verbose_name='Etapa')),
            ],
            options={
                'verbose_name': 'Etapa de Sesión',
                'verbose_name_plural': 'Etapas de Sesión',
                'db_table': 'session_stages',
            },
        ),
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablet_code', models.CharField(max_length=50, unique=True, verbose_name='Código de Tablet')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tablet',
                'verbose_name_plural': 'Tablets',
                'db_table': 'tablets',
                'indexes': [models.Index(fields=['tablet_code'], name='tablets_tablet__9cb635_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeamPersonalization',
            fields=[
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='personalization', serialize=False, to='game_sessions.team', verbose_name='Equipo')),
                ('team_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Equipo')),
                ('team_members_know_each_other', models.BooleanField(blank=True, null=True, verbose_name='Los miembros se conocen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Personalización del Equipo',
                'verbose_name_plural': 'Personalizaciones de Equipos',
                'db_table': 'team_personalization',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='game_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='game_sessions.gamesession', verbose_name='Sesión de Juego'),
        ),
        migrations.CreateModel(
            name='TabletConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected_at', models.DateTimeField(auto_now_add=True, verbose_name='Conectada en')),
                ('disconnected_at', models.DateTimeField(blank=True, null=True, verbose_name='Desconectada en')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Última Vez Vista')),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tablet_connections', to='game_sessions.gamesession', verbose_name='Sesión de Juego')),
                ('tablet', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='connections', to='game_sessions.tablet', verbose_name='Tablet')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tablet_connections', to='game_sessions.team', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Conexión de Tablet',
                'verbose_name_plural': 'Conexiones de Tablets',
                'db_table': 'tablet_connections',
            },
        ),
        migrations.CreateModel(
            name='PeerEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_scores', models.JSONField(verbose_name='Puntuaciones por Criterio')),
                ('total_score', models.IntegerField(verbose_name='Puntuación Total')),
                ('tokens_awarded', models.IntegerField(default=0, verbose_name='Tokens Otorgados')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Feedback')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado en')),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_evaluations', to='game_sessions.gamesession', verbose_name='Sesión de Juego')),
                ('evaluated_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_received', to='game_sessions.team', verbose_name='Equipo Evaluado')),
                ('evaluator_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_given', to='game_sessions.team', verbose_name='Equipo Evaluador')),
            ],
            options={
                'verbose_name': 'Evaluación Peer',
                'verbose_name_plural': 'Evaluaciones Peer',
                'db_table': 'peer_evaluations',
            },
        ),
        migrations.CreateModel(
            name='TeamActivityProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Progreso'), ('submitted', 'Entregado'), ('completed', 'Completado')], default='pending', max_length=20, verbose_name='Estado')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciada en')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completada en')),
                ('progress_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de Progreso')),
                ('response_data', models.JSONField(blank=True, null=True, verbose_name='Datos de Respuesta')),
                ('prototype_image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Imagen del Prototipo')),
                ('pitch_intro_problem', models.TextField(blank=True, null=True, verbose_name='Pitch: Introducción del Problema')),
                ('pitch_solution', models.TextField(blank=True, null=True, verbose_name='Pitch: Solución')),
                ('pitch_closing', models.TextField(blank=True, null=True, verbose_name='Pitch: Cierre')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='team_progress', to='challenges.activity', verbose_name='Actividad')),
                ('selected_challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_in_activities', to='challenges.challenge', verbose_name='Desafío Seleccionado')),
                ('selected_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_in_activities', to='challenges.topic', verbose_name='Tema Seleccionado')),
                ('session_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_activities', to='game_sessions.sessionstage', verbose_name='Etapa de Sesión')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_progress', to='game_sessions.team', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Progreso de Actividad del Equipo',
                'verbose_name_plural': 'Progresos de Actividades de Equipos',
                'db_table': 'team_activity_progress',
            },
        ),
        migrations.CreateModel(
            name='TeamRouletteAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Asignado'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado'), ('completed', 'Completado'), ('failed', 'Fallido')], default='assigned', max_length=20, verbose_name='Estado')),
                ('token_reward', models.IntegerField(default=0, verbose_name='Recompensa en Tokens')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Asignado en')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Aceptado en')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Rechazado en')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado en')),
                ('roulette_challenge', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='assignments', to='challenges.roulettechallenge', verbose_name='Reto de Ruleta')),
                ('session_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roulette_assignments', to='game_sessions.sessionstage', verbose_name='Etapa de Sesión')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roulette_assignments', to='game_sessions.team', verbose_name='Equipo')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_roulette_challenges', to='users.professor', verbose_name='Validado por')),
            ],
            options={
                'verbose_name': 'Asignación de Reto de Ruleta',
                'verbose_name_plural': 'Asignaciones de Retos de Ruleta',
                'db_table': 'team_roulette_assignments',
            },
        ),
        migrations.CreateModel(
            name='TeamStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_students', to='users.student')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_students', to='game_sessions.team')),
            ],
            options={
                'db_table': 'team_students',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='students',
            field=models.ManyToManyField(related_name='teams', through='game_sessions.TeamStudent', to='users.student', verbose_name='Estudiantes'),
        ),
        migrations.CreateModel(
            name='TokenTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Cantidad')),
                ('source_type', models.CharField(choices=[('activity', 'Actividad'), ('roulette_challenge', 'Reto de Ruleta'), ('peer_evaluation', 'Evaluación Peer'), ('manual_adjustment', 'Ajuste Manual'), ('system', 'Sistema')], max_length=30, verbose_name='Tipo de Fuente')),
                ('source_id', models.IntegerField(blank=True, null=True, verbose_name='ID de Fuente')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Razón')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_tokens', to='users.professor', verbose_name='Otorgado por')),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_transactions', to='game_sessions.gamesession', verbose_name='Sesión de Juego')),
                ('session_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_transactions', to='game_sessions.sessionstage', verbose_name='Etapa de Sesión')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_transactions', to='game_sessions.team', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Transacción de Tokens',
                'verbose_name_plural': 'Transacciones de Tokens',
                'db_table': 'token_transactions',
            },
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['professor'], name='game_sessio_profess_2d4bd5_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['room_code'], name='game_sessio_room_co_529049_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['status'], name='game_sessio_status_381f09_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['status', 'started_at'], name='game_sessio_status_972612_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionstage',
            index=models.Index(fields=['game_session'], name='session_sta_game_se_80d31a_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionstage',
            index=models.Index(fields=['stage'], name='session_sta_stage_i_9da390_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionstage',
            index=models.Index(fields=['status'], name='session_sta_status_9dc993_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionstage',
            unique_together={('game_session', 'stage')},
        ),
        migrations.AddIndex(
            model_name='tabletconnection',
            index=models.Index(fields=['tablet'], name='tablet_conn_tablet__aebeaa_idx'),
        ),
        migrations.AddIndex(
            model_name='tabletconnection',
            index=models.Index(fields=['team'], name='tablet_conn_team_id_842e97_idx'),
        ),
        migrations.AddIndex(
            model_name='tabletconnection',
            index=models.Index(fields=['game_session'], name='tablet_conn_game_se_380fa9_idx'),
        ),
        migrations.AddIndex(
            model_name='tabletconnection',
            index=models.Index(fields=['last_seen'], name='tablet_conn_last_se_be9684_idx'),
        ),
        migrations.AddIndex(
            model_name='peerevaluation',
            index=models.Index(fields=['evaluator_team'], name='peer_evalua_evaluat_41ec08_idx'),
        ),
        migrations.AddIndex(
            model_name='peerevaluation',
            index=models.Index(fields=['evaluated_team'], name='peer_evalua_evaluat_813a7f_idx'),
        ),
        migrations.AddIndex(
            model_name='peerevaluation',
            index=models.Index(fields=['game_session'], name='peer_evalua_game_se_cf2369_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='peerevaluation',
            unique_together={('evaluator_team', 'evaluated_team', 'game_session')},
        ),
        migrations.AddIndex(
            model_name='teamactivityprogress',
            index=models.Index(fields=['team'], name='team_activi_team_id_2c8afb_idx'),
        ),
        migrations.AddIndex(
            model_name='teamactivityprogress',
            index=models.Index(fields=['session_stage'], name='team_activi_session_0d2b15_idx'),
        ),
        migrations.AddIndex(
            model_name='teamactivityprogress',
            index=models.Index(fields=['activity'], name='team_activi_activit_e95388_idx'),
        ),
        migrations.AddIndex(
            model_name='teamactivityprogress',
            index=models.Index(fields=['status'], name='team_activi_status_00750a_idx'),
        ),
        migrations.AddIndex(
            model_name='teamactivityprogress',
            index=models.Index(fields=['team', 'activity'], name='team_activi_team_id_d1bada_idx'),
        ),
        migrations.AddIndex(
            model_name='teamactivityprogress',
            index=models.Index(fields=['session_stage', 'activity'], name='team_activi_session_1a4ca1_idx'),
        ),
        migrations.AddIndex(
            model_name='teamrouletteassignment',
            index=models.Index(fields=['team'], name='team_roulet_team_id_af552c_idx'),
        ),
        migrations.AddIndex(
            model_name='teamrouletteassignment',
            index=models.Index(fields=['roulette_challenge'], name='team_roulet_roulett_8c9155_idx'),
        ),
        migrations.AddIndex(
            model_name='teamrouletteassignment',
            index=models.Index(fields=['status'], name='team_roulet_status_d5a38d_idx'),
        ),
        migrations.AddIndex(
            model_name='teamstudent',
            index=models.Index(fields=['student'], name='team_studen_student_28cbe0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teamstudent',
            unique_together={('team', 'student')},
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['game_session'], name='teams_game_se_7d8aab_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['color'], name='teams_color_56beec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('game_session', 'name')},
        ),
        migrations.AddIndex(
            model_name='tokentransaction',
            index=models.Index(fields=['team'], name='token_trans_team_id_901680_idx'),
        ),
        migrations.AddIndex(
            model_name='tokentransaction',
            index=models.Index(fields=['game_session'], name='token_trans_game_se_6b0306_idx'),
        ),
        migrations.AddIndex(
            model_name='tokentransaction',
            index=models.Index(fields=['source_type', 'source_id'], name='token_trans_source__621a3e_idx'),
        ),
        migrations.AddIndex(
            model_name='tokentransaction',
            index=models.Index(fields=['created_at'], name='token_trans_created_4c5cdd_idx'),
        ),
    ]
