# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0002_remove_duplicate_progress'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamactivityprogress',
            unique_together={('team', 'activity', 'session_stage')},
        ),
    ]

