# Generated by Django 5.0.14 on 2025-11-04 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0003_alter_teamactivityprogress_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamBubbleMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_data', models.JSONField(verbose_name='Datos del Mapa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bubble_maps', to='game_sessions.sessionstage', verbose_name='Etapa de Sesión')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bubble_maps', to='game_sessions.team', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Bubble Map del Equipo',
                'verbose_name_plural': 'Bubble Maps de Equipos',
                'db_table': 'team_bubble_maps',
                'indexes': [models.Index(fields=['team'], name='team_bubble_team_id_9bb24e_idx'), models.Index(fields=['session_stage'], name='team_bubble_session_86d871_idx')],
                'unique_together': {('team', 'session_stage')},
            },
        ),
    ]
