# Generated by Django 5.0.14 on 2025-11-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0004_teambubblemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionstage',
            name='current_presentation_team_id',
            field=models.IntegerField(blank=True, help_text='ID del equipo que está presentando actualmente (Etapa 4)', null=True, verbose_name='ID del Equipo Presentando Actualmente'),
        ),
        migrations.AddField(
            model_name='sessionstage',
            name='presentation_order',
            field=models.JSONField(blank=True, help_text='Array de IDs de equipos en orden de presentación (Etapa 4)', null=True, verbose_name='Orden de Presentación'),
        ),
    ]
