# Generated by Django 5.0.14 on 2025-11-14 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0007_sessionstage_presentation_timestamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReflectionEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200, verbose_name='Nombre y Apellido')),
                ('student_email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('career', models.CharField(blank=True, max_length=200, null=True, verbose_name='Carrera')),
                ('value_areas', models.JSONField(default=list, help_text='Resolver desafíos, Trabajar en equipo, Empatizar, etc.', verbose_name='Áreas de Valor')),
                ('satisfaction', models.CharField(blank=True, choices=[('mucho', 'Sí, mucho'), ('si', 'Sí'), ('masomenos', 'Más o menos'), ('nomucho', 'No mucho'), ('no', 'No')], max_length=50, null=True, verbose_name='Te gustó la actividad realizada?')),
                ('entrepreneurship_interest', models.CharField(blank=True, choices=[('ya_tenia', 'Ya tenía ganas de emprender antes de la actividad'), ('me_encantaria', 'Sí, me encantaría emprender'), ('posible_opcion', 'Ahora lo veo como una posible opción'), ('no_interesa', 'No, sigue sin interesarme')], max_length=50, null=True, verbose_name='¿Se incrementaron tus ganas de querer emprender?')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comentarios sobre la actividad o intereses')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_evaluations', to='game_sessions.gamesession', verbose_name='Sesión de Juego')),
            ],
            options={
                'verbose_name': 'Evaluación de Reflexión',
                'verbose_name_plural': 'Evaluaciones de Reflexión',
                'db_table': 'reflection_evaluations',
                'indexes': [models.Index(fields=['game_session'], name='reflection__game_se_728398_idx'), models.Index(fields=['student_email'], name='reflection__student_836c1c_idx')],
            },
        ),
    ]
