# Generated by Django 5.0.14 on 2025-11-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0011_teamactivityprogress_pitch_value_and_pitch_impact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamactivityprogress',
            name='pitch_intro_problem',
            field=models.TextField(blank=True, null=True, verbose_name='Pitch: Problema'),
        ),
    ]
