# Generated by Django 5.0.14 on 2025-11-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('challenges', '0007_challenge_persona_image'),
        ('game_sessions', '0013_gamesession_cancellation_reason_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['created_at'], name='game_sessio_created_7179a2_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['course'], name='game_sessio_course__601678_idx'),
        ),
    ]
