# Generated by Django 5.0.14 on 2025-12-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0014_gamesession_game_sessio_created_7179a2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teampersonalization',
            name='logo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Logo de la Startup'),
        ),
    ]
