# Generated by Django 5.0.14 on 2026-04-13 14:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0016_remove_logo_from_team_personalization'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabletconnection',
            name='team_session_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token de Sesión de Equipo'),
        ),
        migrations.AlterField(
            model_name='tabletconnection',
            name='tablet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connections', to='game_sessions.tablet', verbose_name='Tablet'),
        ),
    ]
