# Generated by Django 5.0.14 on 2025-11-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0006_sessionstage_presentation_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionstage',
            name='presentation_timestamps',
            field=models.JSONField(blank=True, help_text='Diccionario con timestamps de inicio de cada presentación: {team_id: timestamp} (Etapa 4)', null=True, verbose_name='Timestamps de Presentaciones'),
        ),
    ]
