# Generated by Django 5.0.14 on 2025-11-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0008_reflectionevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reflectionevaluation',
            name='faculty',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Facultad'),
        ),
        migrations.AlterField(
            model_name='reflectionevaluation',
            name='student_email',
            field=models.EmailField(max_length=254, verbose_name='Correo UDD'),
        ),
    ]
