# Generated by Django 5.0.14 on 2025-11-14 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('game_sessions', '0009_reflectionevaluation_faculty_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.IntegerField(verbose_name='Total de Estudiantes')),
                ('number_of_sessions', models.IntegerField(verbose_name='Número de Salas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='session_groups', to='academic.course', verbose_name='Curso')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='session_groups', to='users.professor', verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Grupo de Sesiones',
                'verbose_name_plural': 'Grupos de Sesiones',
                'db_table': 'session_groups',
            },
        ),
        migrations.AddField(
            model_name='gamesession',
            name='session_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_sessions', to='game_sessions.sessiongroup', verbose_name='Grupo de Sesiones'),
        ),
        migrations.AddIndex(
            model_name='sessiongroup',
            index=models.Index(fields=['professor'], name='session_gro_profess_20eb21_idx'),
        ),
        migrations.AddIndex(
            model_name='sessiongroup',
            index=models.Index(fields=['course'], name='session_gro_course__2145cd_idx'),
        ),
    ]
