# Generated by Django 5.0.14 on 2025-11-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0012_alter_teamactivityprogress_pitch_intro_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='cancellation_reason',
            field=models.CharField(blank=True, help_text='Motivo por el cual se canceló la sesión', max_length=50, null=True, verbose_name='Motivo de Cancelación'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='cancellation_reason_other',
            field=models.TextField(blank=True, help_text='Descripción adicional si se seleccionó "Otro" como motivo', null=True, verbose_name='Motivo de Cancelación (Otro)'),
        ),
    ]
