# Generated by Django 5.0.14 on 2025-12-02 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0015_add_logo_to_team_personalization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teampersonalization',
            name='logo',
        ),
    ]
