# Generated by Django 5.0.14 on 2025-11-26 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activitydurationmetric',
            new_name='activity_du_activit_444351_idx',
            old_name='activity_du_activit_idx',
        ),
        migrations.RenameIndex(
            model_name='activitydurationmetric',
            new_name='activity_du_stage_i_98cff4_idx',
            old_name='activity_du_stage_i_idx',
        ),
        migrations.RenameIndex(
            model_name='dailymetricssnapshot',
            new_name='daily_metri_date_3f4067_idx',
            old_name='daily_metr_date_idx',
        ),
    ]
