# Generated by Django 5.0.14 on 2025-11-04 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
                'db_table': 'faculties',
                'indexes': [models.Index(fields=['is_active'], name='faculties_is_acti_5069b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='careers', to='academic.faculty', verbose_name='Facultad')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'db_table': 'careers',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='courses', to='academic.career', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'courses',
                'indexes': [models.Index(fields=['career'], name='courses_career__131c4c_idx'), models.Index(fields=['is_active'], name='courses_is_acti_25e634_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='career',
            index=models.Index(fields=['faculty'], name='careers_faculty_58893f_idx'),
        ),
        migrations.AddIndex(
            model_name='career',
            index=models.Index(fields=['is_active'], name='careers_is_acti_c4cbef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='career',
            unique_together={('faculty', 'name')},
        ),
    ]
