# Generated by Django 5.0.14 on 2025-11-04 00:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Actividad',
                'verbose_name_plural': 'Tipos de Actividades',
                'db_table': 'activity_types',
                'indexes': [models.Index(fields=['code'], name='activity_ty_code_0cb432_idx')],
            },
        ),
        migrations.CreateModel(
            name='Minigame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('type', models.CharField(choices=[('word_search', 'Sopa de Letras'), ('puzzle', 'Puzzle'), ('other', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('config', models.JSONField(blank=True, null=True, verbose_name='Configuración')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Minijuego',
                'verbose_name_plural': 'Minijuegos',
                'db_table': 'minigames',
                'indexes': [models.Index(fields=['is_active'], name='minigames_is_acti_7fdda0_idx')],
            },
        ),
        migrations.CreateModel(
            name='RouletteChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('challenge_type', models.CharField(choices=[('physical', 'Físico'), ('mental', 'Mental'), ('creative', 'Creativo'), ('other', 'Otro')], max_length=20, verbose_name='Tipo de Reto')),
                ('difficulty_estimated', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Dificultad Estimada (1-10)')),
                ('token_reward_min', models.IntegerField(default=0, verbose_name='Recompensa Mínima en Tokens')),
                ('token_reward_max', models.IntegerField(default=0, verbose_name='Recompensa Máxima en Tokens')),
                ('stages_applicable', models.JSONField(blank=True, null=True, verbose_name='Etapas Aplicables')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reto de Ruleta',
                'verbose_name_plural': 'Retos de Ruleta',
                'db_table': 'roulette_challenges',
                'indexes': [models.Index(fields=['challenge_type'], name='roulette_ch_challen_ddbd15_idx'), models.Index(fields=['is_active'], name='roulette_ch_is_acti_977e2a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Número')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('objective', models.TextField(blank=True, null=True, verbose_name='Objetivo')),
                ('estimated_duration', models.IntegerField(blank=True, null=True, verbose_name='Duración Estimada (minutos)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'db_table': 'stages',
                'ordering': ['number'],
                'indexes': [models.Index(fields=['number'], name='stages_number_09a69d_idx'), models.Index(fields=['is_active'], name='stages_is_acti_aa6986_idx')],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Imagen')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoría')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculties', models.ManyToManyField(related_name='topics', to='academic.faculty', verbose_name='Facultades')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'db_table': 'topics',
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('user_story', models.TextField(verbose_name='Historia de Usuario')),
                ('difficulty_level', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=20, verbose_name='Nivel de Dificultad')),
                ('learning_objectives', models.TextField(blank=True, null=True, verbose_name='Objetivos de Aprendizaje')),
                ('additional_resources', models.TextField(blank=True, null=True, verbose_name='Recursos Adicionales')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='challenges', to='challenges.topic', verbose_name='Tema')),
            ],
            options={
                'verbose_name': 'Desafío',
                'verbose_name_plural': 'Desafíos',
                'db_table': 'challenges',
            },
        ),
        migrations.CreateModel(
            name='LearningObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('evaluation_criteria', models.TextField(blank=True, null=True, verbose_name='Criterios de Evaluación')),
                ('pedagogical_recommendations', models.TextField(blank=True, null=True, verbose_name='Recomendaciones Pedagógicas')),
                ('estimated_time', models.IntegerField(blank=True, null=True, verbose_name='Tiempo Estimado (minutos)')),
                ('associated_resources', models.TextField(blank=True, null=True, verbose_name='Recursos Asociados')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_objectives', to='challenges.stage', verbose_name='Etapa')),
            ],
            options={
                'verbose_name': 'Objetivo de Aprendizaje',
                'verbose_name_plural': 'Objetivos de Aprendizaje',
                'db_table': 'learning_objectives',
                'indexes': [models.Index(fields=['stage'], name='learning_ob_stage_i_1b85ec_idx'), models.Index(fields=['is_active'], name='learning_ob_is_acti_0b73ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('order_number', models.IntegerField(verbose_name='Número de Orden')),
                ('timer_duration', models.IntegerField(blank=True, null=True, verbose_name='Duración del Temporizador (segundos)')),
                ('config_data', models.JSONField(blank=True, null=True, verbose_name='Datos de Configuración')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='activities', to='challenges.activitytype', verbose_name='Tipo de Actividad')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='activities', to='challenges.stage', verbose_name='Etapa')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'activities',
                'ordering': ['stage', 'order_number'],
                'indexes': [models.Index(fields=['stage'], name='activities_stage_i_7425c6_idx'), models.Index(fields=['activity_type'], name='activities_activit_a33aa7_idx'), models.Index(fields=['stage', 'order_number'], name='activities_stage_i_f1817d_idx')],
                'unique_together': {('stage', 'order_number')},
            },
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['is_active'], name='topics_is_acti_45fe00_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['category'], name='topics_categor_7de43b_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['topic'], name='challenges_topic_i_f14e19_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['difficulty_level'], name='challenges_difficu_238107_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['is_active'], name='challenges_is_acti_5318b2_idx'),
        ),
    ]
