# Generated by Django 5.0.14 on 2025-11-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji o símbolo para representar el desafío (ej: 💰, 🎓, 📱)', max_length=10, null=True, verbose_name='Icono'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='persona_age',
            field=models.IntegerField(blank=True, help_text='Edad de la persona en la historia de usuario', null=True, verbose_name='Edad de la Persona'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='persona_name',
            field=models.CharField(blank=True, help_text='Nombre de la persona en la historia de usuario', max_length=100, null=True, verbose_name='Nombre de la Persona'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='persona_story',
            field=models.TextField(blank=True, help_text='Cita o historia específica de la persona', null=True, verbose_name='Historia de la Persona'),
        ),
    ]
