# Generated by Django 5.0.14 on 2025-11-06 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_add_challenge_icon_and_persona'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='user_story',
        ),
    ]
