# Generated by Django 5.0.14 on 2025-11-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_remove_user_story_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción del problema o desafío que se busca resolver', null=True, verbose_name='Descripción del Desafío'),
        ),
    ]
