# Generated by Django 5.0.14 on 2025-11-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_wordsearchoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='persona_image',
            field=models.ImageField(blank=True, help_text='Imagen de perfil de la persona del desafío', null=True, upload_to='personas/', verbose_name='Imagen de la Persona'),
        ),
    ]
