# Generated by Django 5.0.14 on 2025-11-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_challenge_persona_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordsearchoption',
            name='grid',
            field=models.JSONField(blank=True, help_text='Matriz 12x12 de la sopa de letras generada', null=True, verbose_name='Grid Generado'),
        ),
        migrations.AddField(
            model_name='wordsearchoption',
            name='seed',
            field=models.IntegerField(blank=True, help_text='Semilla usada para generar esta sopa de letras', null=True, verbose_name='Semilla'),
        ),
        migrations.AddField(
            model_name='wordsearchoption',
            name='word_positions',
            field=models.JSONField(blank=True, help_text='Lista de posiciones de cada palabra en el grid', null=True, verbose_name='Posiciones de Palabras'),
        ),
        migrations.AlterField(
            model_name='wordsearchoption',
            name='words',
            field=models.JSONField(help_text='Lista de palabras para esta sopa de letras (máximo 5 palabras)', verbose_name='Palabras'),
        ),
        migrations.CreateModel(
            name='AnagramWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Palabra')),
                ('scrambled_word', models.CharField(blank=True, help_text='Se genera automáticamente al guardar', max_length=100, null=True, verbose_name='Palabra Desordenada')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Palabra de Anagrama',
                'verbose_name_plural': 'Palabras de Anagrama',
                'db_table': 'anagram_words',
                'ordering': ['word'],
                'indexes': [models.Index(fields=['is_active'], name='anagram_wor_is_acti_e5207d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChaosQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Pregunta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pregunta del Caos',
                'verbose_name_plural': 'Preguntas del Caos',
                'db_table': 'chaos_questions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='chaos_quest_is_acti_ed3ea2_idx')],
            },
        ),
        migrations.CreateModel(
            name='GeneralKnowledgeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Pregunta')),
                ('option_a', models.CharField(max_length=255, verbose_name='Opción A')),
                ('option_b', models.CharField(max_length=255, verbose_name='Opción B')),
                ('option_c', models.CharField(max_length=255, verbose_name='Opción C')),
                ('option_d', models.CharField(max_length=255, verbose_name='Opción D')),
                ('correct_answer', models.IntegerField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D')], verbose_name='Respuesta Correcta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pregunta de Conocimiento General',
                'verbose_name_plural': 'Preguntas de Conocimiento General',
                'db_table': 'general_knowledge_questions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='general_kno_is_acti_092043_idx')],
            },
        ),
    ]
