# Dockerfile para Frontend React/Vite (Desarrollo)
FROM node:20-alpine3.19

WORKDIR /app

COPY frontend/package*.json ./
RUN npm ci

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

