# Generated by Django 5.0.14 on 2025-11-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_add_challenge_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji o símbolo para representar el tema (ej: 🏥, 💰, 🌱)', max_length=10, null=True, verbose_name='Icono'),
        ),
    ]
