# Generated by Django 5.0.14 on 2025-11-16 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_add_topic_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordSearchOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo para identificar esta opción de sopa de letras', max_length=100, verbose_name='Nombre de la opción')),
                ('words', models.JSONField(help_text='Lista de palabras para esta sopa de letras (mínimo 5 palabras)', verbose_name='Palabras')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_search_options', to='challenges.activity', verbose_name='Actividad')),
            ],
            options={
                'verbose_name': 'Opción de Sopa de Letras',
                'verbose_name_plural': 'Opciones de Sopa de Letras',
                'db_table': 'word_search_options',
                'ordering': ['activity', 'name'],
                'indexes': [models.Index(fields=['activity', 'is_active'], name='word_search_activit_21d157_idx')],
            },
        ),
    ]
